title: <p align="center">Anish Kumar Dubey</p>
logo: /assets/img/ProfilePhoto.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
